export const SENSIBILIZACION_SHEET_NAME = "8. SENSIBILIZACIÓN";
export const SENSIBILIZACION_OBSERVACIONES_CELL = "A26";
export const SENSIBILIZACION_ATTENDEES_START_ROW = 32;
export const SENSIBILIZACION_ATTENDEES_BASE_ROWS = 4;
export const SENSIBILIZACION_ATTENDEES_NAME_COL = "C";
export const SENSIBILIZACION_ATTENDEES_CARGO_COL = "K";
