import { describe, it, expect } from "vitest";
import { odsPayloadSchema, odsPayloadBaseSchema, usuarioNuevoSchema } from "./schemas";

const ODS_COLUMNS = [
  "id",
  "id_servicio",
  "codigo_servicio",
  "referencia_servicio",
  "descripcion_servicio",
  "nombre_profesional",
  "nombre_empresa",
  "nit_empresa",
  "caja_compensacion",
  "asesor_empresa",
  "sede_empresa",
  "fecha_servicio",
  "fecha_ingreso",
  "mes_servicio",
  "ano_servicio",
  "nombre_usuario",
  "cedula_usuario",
  "discapacidad_usuario",
  "genero_usuario",
  "modalidad_servicio",
  "todas_modalidades",
  "horas_interprete",
  "valor_virtual",
  "valor_bogota",
  "valor_otro",
  "valor_interprete",
  "valor_total",
  "tipo_contrato",
  "cargo_servicio",
  "seguimiento_servicio",
  "orden_clausulada",
  "total_personas",
  "observaciones",
  "observacion_agencia",
  "created_at",
  "updated_at",
  "session_id",
  "started_at",
  "submitted_at",
  "formato_finalizado_id",
  "user_id",
];

const ODS_NOT_NULL_COLUMNS = [
  "id",
  "codigo_servicio",
  "referencia_servicio",
  "descripcion_servicio",
  "nombre_profesional",
  "nombre_empresa",
  "nit_empresa",
  "fecha_servicio",
  "mes_servicio",
  "ano_servicio",
  "modalidad_servicio",
  "valor_total",
  "orden_clausulada",
];

const USUARIOS_RECA_COLUMNS = [
  "id",
  "cedula_usuario",
  "nombre_usuario",
  "discapacidad_usuario",
  "genero_usuario",
  "fecha_ingreso",
  "tipo_contrato",
  "cargo_servicio",
  "created_at",
  "updated_at",
];

function getOdsPayloadKeys(): string[] {
  return Object.keys(odsPayloadBaseSchema.shape);
}

function getUsuarioNuevoKeys(): string[] {
  const shape = usuarioNuevoSchema.shape;
  return Object.keys(shape);
}

function validBase() {
  return {
    orden_clausulada: "si" as const,
    nombre_profesional: "Test",
    nit_empresa: "123",
    nombre_empresa: "Test Corp",
    fecha_servicio: "2025-06-15",
    codigo_servicio: "1",
    referencia_servicio: "Ref",
    descripcion_servicio: "Desc",
    modalidad_servicio: "Virtual" as const,
    valor_interprete: 100,
    valor_total: 100,
    mes_servicio: 6,
    ano_servicio: 2025,
  };
}

describe("Zod schema drift vs Supabase schema", () => {
  describe("OdsPayload", () => {
    it("no tiene campos que no existan en la BD", () => {
      const zodKeys = getOdsPayloadKeys();
      const extraFields = zodKeys.filter(
        (key) => !ODS_COLUMNS.includes(key)
      );
      expect(extraFields).toEqual([]);
    });

    it("incluye todos los campos NOT NULL de la BD (excepto auto-generados)", () => {
      const zodKeys = getOdsPayloadKeys();
      const autoGenerated = new Set([
        "id",
        "created_at",
        "updated_at",
      ]);
      const missingFields = ODS_NOT_NULL_COLUMNS.filter(
        (col) => !autoGenerated.has(col) && !zodKeys.includes(col)
      );
      expect(missingFields).toEqual([]);
    });

    it("tiene mes_servicio entre 1 y 12", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        mes_servicio: 13,
      });
      expect(result.success).toBe(false);
    });

    it("rechaza orden_clausulada fuera de 'si'/'no'", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        orden_clausulada: "yes" as never,
      });
      expect(result.success).toBe(false);
    });

    it("rechaza modalidad_servicio fuera del enum", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        modalidad_servicio: "Presencial" as never,
      });
      expect(result.success).toBe(false);
    });

    it("valida formato_finalizado_id como UUID si presente", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        formato_finalizado_id: "not-a-uuid",
      });
      expect(result.success).toBe(false);
    });

    it("valida session_id como UUID si presente", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        session_id: "not-a-uuid",
      });
      expect(result.success).toBe(false);
    });

    it("valida valor_total ≈ suma de modalidades cuando no es interprete", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        valor_interprete: 0,
        valor_virtual: 50,
        valor_total: 200,
      });
      expect(result.success).toBe(false);
    });

    it("valida submitted_at >= started_at cuando ambos presentes", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        started_at: "2025-06-15T10:00:00Z",
        submitted_at: "2025-06-15T09:00:00Z",
      });
      expect(result.success).toBe(false);
    });

    it("acecta payload valido minimo", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        valor_virtual: 100,
      });
      expect(result.success).toBe(true);
    });
  });

  describe("UsuarioNuevo", () => {
    it("no tiene campos que no existan en la BD", () => {
      const zodKeys = getUsuarioNuevoKeys();
      const extraFields = zodKeys.filter(
        (key) => !USUARIOS_RECA_COLUMNS.includes(key)
      );
      expect(extraFields).toEqual([]);
    });

    it("requiere cedula_usuario", () => {
      const result = usuarioNuevoSchema.safeParse({
        nombre_usuario: "Test",
        discapacidad_usuario: "Fisica",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(false);
    });

    it("acecta usuario nuevo minimo", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "12345678",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Fisica",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(true);
    });
  });
});
