import { describe, it, expect } from "vitest";
import { odsPayloadSchema, odsPayloadBaseSchema, usuarioNuevoSchema, terminarServicioRequestSchema } from "./schemas";
import { DISCAPACIDADES, GENEROS, TIPOS_CONTRATO } from "./catalogs";

// NOTA: estos arrays son hardcodeados. Un drift test verdadero (que lea
// information_schema en runtime) queda como deuda tecnica documentada
// para una iteracion futura. Por ahora el snapshot manual es suficiente
// mientras el schema sea estable.

const ODS_COLUMNS = [
  "id",
  "id_servicio",
  "codigo_servicio",
  "referencia_servicio",
  "descripcion_servicio",
  "nombre_profesional",
  "nombre_empresa",
  "nit_empresa",
  "caja_compensacion",
  "asesor_empresa",
  "sede_empresa",
  "fecha_servicio",
  "fecha_ingreso",
  "mes_servicio",
  "ano_servicio",
  "nombre_usuario",
  "cedula_usuario",
  "discapacidad_usuario",
  "genero_usuario",
  "modalidad_servicio",
  "todas_modalidades",
  "horas_interprete",
  "valor_virtual",
  "valor_bogota",
  "valor_otro",
  "valor_interprete",
  "valor_total",
  "tipo_contrato",
  "cargo_servicio",
  "seguimiento_servicio",
  "orden_clausulada",
  "total_personas",
  "observaciones",
  "observacion_agencia",
  "created_at",
  "updated_at",
  "session_id",
  "started_at",
  "submitted_at",
  "formato_finalizado_id",
  "user_id",
];

const ODS_BUSINESS_REQUIRED_COLUMNS = [
  "id",
  "codigo_servicio",
  "referencia_servicio",
  "descripcion_servicio",
  "nombre_profesional",
  "nombre_empresa",
  "nit_empresa",
  "fecha_servicio",
  "mes_servicio",
  "ano_servicio",
  "modalidad_servicio",
  "valor_total",
  "orden_clausulada",
];

const USUARIOS_RECA_COLUMNS = [
  "id",
  "cedula_usuario",
  "nombre_usuario",
  "discapacidad_usuario",
  "genero_usuario",
  "fecha_ingreso",
  "tipo_contrato",
  "cargo_servicio",
  "created_at",
  "updated_at",
];

function getOdsPayloadKeys(): string[] {
  return Object.keys(odsPayloadBaseSchema.shape);
}

function getUsuarioNuevoKeys(): string[] {
  const shape = usuarioNuevoSchema.shape;
  return Object.keys(shape);
}

function validBase() {
  return {
    orden_clausulada: "si" as const,
    nombre_profesional: "Test",
    nit_empresa: "123",
    nombre_empresa: "Test Corp",
    fecha_servicio: "2025-06-15",
    codigo_servicio: "1",
    referencia_servicio: "Ref",
    descripcion_servicio: "Desc",
    modalidad_servicio: "Virtual" as const,
    valor_interprete: 100,
    valor_total: 100,
    mes_servicio: 6,
    ano_servicio: 2025,
  };
}

describe("Zod schema drift vs Supabase schema", () => {
  describe("OdsPayload", () => {
    it("no tiene campos que no existan en la BD", () => {
      const zodKeys = getOdsPayloadKeys();
      const extraFields = zodKeys.filter(
        (key) => !ODS_COLUMNS.includes(key)
      );
      expect(extraFields).toEqual([]);
    });

    it("incluye todos los campos obligatorios del negocio", () => {
      const zodKeys = getOdsPayloadKeys();
      const autoGenerated = new Set([
        "id",
        "created_at",
        "updated_at",
      ]);
      const missingFields = ODS_BUSINESS_REQUIRED_COLUMNS.filter(
        (col) => !autoGenerated.has(col) && !zodKeys.includes(col)
      );
      expect(missingFields).toEqual([]);
    });

    it("tiene mes_servicio entre 1 y 12", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        mes_servicio: 13,
      });
      expect(result.success).toBe(false);
    });

    it("rechaza orden_clausulada fuera de 'si'/'no'", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        orden_clausulada: "yes" as never,
      });
      expect(result.success).toBe(false);
    });

    it("rechaza modalidad_servicio fuera del enum", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        modalidad_servicio: "Presencial" as never,
      });
      expect(result.success).toBe(false);
    });

    it("valida formato_finalizado_id como UUID si presente", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        formato_finalizado_id: "not-a-uuid",
      });
      expect(result.success).toBe(false);
    });

    it("valida session_id como UUID si presente", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        session_id: "not-a-uuid",
      });
      expect(result.success).toBe(false);
    });

    it("rechaza telemetria_id dentro de ods para no contaminar el payload BD", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        valor_virtual: 100,
        telemetria_id: "55555555-5555-4555-8555-555555555555",
      });
      expect(result.success).toBe(true);
      if (result.success) {
        expect("telemetria_id" in result.data).toBe(false);
      }
    });

    it("valida valor_total ≈ suma de modalidades cuando no es interprete", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        valor_interprete: 0,
        valor_virtual: 50,
        valor_total: 200,
      });
      expect(result.success).toBe(false);
    });

    it("rechaza valor_total = suma de modalidades cuando hay interprete > 0", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        valor_interprete: 50,
        valor_virtual: 100,
        valor_total: 100,
      });
      expect(result.success).toBe(false);
    });

    it("valida submitted_at >= started_at cuando ambos presentes", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        started_at: "2025-06-15T10:00:00Z",
        submitted_at: "2025-06-15T09:00:00Z",
      });
      expect(result.success).toBe(false);
    });

    it("acecta payload valido minimo", () => {
      const result = odsPayloadSchema.safeParse({
        ...validBase(),
        valor_virtual: 100,
      });
      expect(result.success).toBe(true);
    });

    it("acepta telemetria_id top-level en terminarServicioRequestSchema", () => {
      const result = terminarServicioRequestSchema.safeParse({
        ods: {
          ...validBase(),
          valor_virtual: 100,
        },
        usuarios_nuevos: [],
        telemetria_id: "55555555-5555-4555-8555-555555555555",
      });
      expect(result.success).toBe(true);
      if (result.success) {
        expect(result.data.telemetria_id).toBe("55555555-5555-4555-8555-555555555555");
      }
    });

    it("rechaza telemetria_id top-level invalido", () => {
      const result = terminarServicioRequestSchema.safeParse({
        ods: {
          ...validBase(),
          valor_virtual: 100,
        },
        usuarios_nuevos: [],
        telemetria_id: "not-a-uuid",
      });
      expect(result.success).toBe(false);
    });
  });

  describe("UsuarioNuevo", () => {
    it("no tiene campos que no existan en la BD", () => {
      const zodKeys = getUsuarioNuevoKeys();
      const extraFields = zodKeys.filter(
        (key) => !USUARIOS_RECA_COLUMNS.includes(key)
      );
      expect(extraFields).toEqual([]);
    });

    it("requiere cedula_usuario", () => {
      const result = usuarioNuevoSchema.safeParse({
        nombre_usuario: "Test",
        discapacidad_usuario: "Fisica",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(false);
    });

    it("acecta usuario nuevo minimo", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "12345678",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Física",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(true);
    });

    it("rechaza genero_usuario 'MUJER' (mayusculas)", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "12345678",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Física",
        genero_usuario: "MUJER",
      });
      expect(result.success).toBe(false);
    });

    it("rechaza genero_usuario 'mujer' (minusculas)", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "12345678",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Física",
        genero_usuario: "mujer",
      });
      expect(result.success).toBe(false);
    });

    it("rechaza discapacidad_usuario 'Multiple' (sin acento)", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "12345678",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Multiple",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(false);
    });

    it("acecta genero_usuario 'Hombre' (catalogo correcto)", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "12345678",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Física",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(true);
    });

    it("valida cedula_usuario solo digitos", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "123abc",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Física",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(false);
    });

    it("acecta todos los valores del catalogo de discapacidades", () => {
      for (const d of DISCAPACIDADES) {
        const result = usuarioNuevoSchema.safeParse({
          cedula_usuario: "12345678",
          nombre_usuario: "Test User",
          discapacidad_usuario: d,
          genero_usuario: "Hombre",
        });
        expect(result.success).toBe(true);
      }
    });

    it("acepta Hipoacusia como discapacidad independiente", () => {
      const result = usuarioNuevoSchema.safeParse({
        cedula_usuario: "12345678",
        nombre_usuario: "Test User",
        discapacidad_usuario: "Hipoacusia",
        genero_usuario: "Hombre",
      });
      expect(result.success).toBe(true);
    });

    it("acecta todos los valores del catalogo de generos", () => {
      for (const g of GENEROS) {
        const result = usuarioNuevoSchema.safeParse({
          cedula_usuario: "12345678",
          nombre_usuario: "Test User",
          discapacidad_usuario: "Física",
          genero_usuario: g,
        });
        expect(result.success).toBe(true);
      }
    });

    it("acecta todos los valores del catalogo de tipos de contrato", () => {
      for (const t of TIPOS_CONTRATO) {
        const result = usuarioNuevoSchema.safeParse({
          cedula_usuario: "12345678",
          nombre_usuario: "Test User",
          discapacidad_usuario: "Física",
          genero_usuario: "Hombre",
          tipo_contrato: t,
        });
        expect(result.success).toBe(true);
      }
    });
  });
});
